apiVersion: v1
kind: Service
metadata:
  name: sasrl-env-service
spec:
  selector:
    app: sasrl-env
  ports:
  - protocol: "TCP"
    port: 20005
    targetPort: 10005
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sasrl-env-python
spec:
  selector:
    matchLabels:
      app: sasrl-env-python
  replicas: 1
  template:
    metadata:
      labels:
        app: sasrl-env-python
    spec:
      containers:
      - name: sasrl-env
        image: docker.sas.com/rl/sasrl-env:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 10005